### ISSUE TITLE
初始化问题

### ISSUE THREAD

**Issue by yusuppunk** [leesinz/crush#1]
作者你好，我在初始化Crush的时候，遇到了这个报错，尝试了科学上网或者全局代理等方法均无果。所以想下，如果我想离线安装的话，需要怎么处理？ 
=========================================
[root@monvul src]# go run main.go 
go: downloading github.com/common-nighthawk/go-figure v0.0.0-20210622060536-734e95fb86be
go: downloading github.com/PuerkitoBio/goquery v1.8.1
go: downloading github.com/fatih/color v1.16.0
go: downloading github.com/chromedp/chromedp v0.9.3
go: downloading github.com/go-sql-driver/mysql v1.7.1
go: downloading gopkg.in/yaml.v2 v2.4.0
config/config.go:5:2: gopkg.in/yaml.v2@v2.4.0: Get "https://proxy.golang.org/gopkg.in/yaml.v2/@v/v2.4.0.zip": dial tcp 142.251.42.241:443: connect: connection refused
utils/crawl.go:5:2: github.com/PuerkitoBio/goquery@v1.8.1: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.8.1.zip": dial tcp 142.251.42.241:443: connect: connection refused
utils/banner.go:5:2: github.com/common-nighthawk/go-figure@v0.0.0-20210622060536-734e95fb86be: Get "https://proxy.golang.org/github.com/common-nighthawk/go-figure/@v/v0.0.0-20210622060536-734e95fb86be.zip": dial tcp 142.251.42.241:443: connect: connection refused
utils/banner.go:6:2: github.com/fatih/color@v1.16.0: Get "https://proxy.golang.org/github.com/fatih/color/@v/v1.16.0.zip": dial tcp 142.251.42.241:443: connect: connection refused
database/0dayDB.go:8:2: github.com/go-sql-driver/mysql@v1.7.1: Get "https://proxy.golang.org/github.com/go-sql-driver/mysql/@v/v1.7.1.zip": dial tcp 142.251.42.241:443: connect: connection refused
crawler/get0dayInfo.go:14:2: github.com/chromedp/chromedp@v0.9.3: Get "https://proxy.golang.org/github.com/chromedp/chromedp/@v/v0.9.3.zip": dial tcp 142.251.42.241:443: connect: connection refused

**Comment by leesinz** [comment]
应该是网络问题，尝试一下海外节点的vps试试看呢，如果还有问题可以邮件联系我 ：)

**Comment by yusuppunk** [comment]
找到方法了，设置一下Golang代理就OK了
`$ go env -w GO111MODULE=on`
`$ go env -w GOPROXY=https://goproxy.io,direc`
